### ISSUE TITLE
Portfolio gradient does not look nice in Safari

### ISSUE THREAD

**Issue by globalcow** [iamdmitrymayorov/maker#4]
Hi Dmitry, in Safari on macOS, [the new gradient definition](https://github.com/dmtrmrv/maker/commit/e8ace335b7041891da042f9fdd63755244291ce3#diff-b83700c56c7f84c57611f8afaf25ec7a) does not look nice. It seems that Safari is fading to transparent black. I attached two screenshots from Safari and Firefox.
Thank you for the great theme! Cheers!

Firefox:
<img width="403" alt="gradient-firefox" src="https://cloud.githubusercontent.com/assets/2294737/20023779/971f3fba-a2e2-11e6-9573-e05f39ad3a3b.png">

Safari:
<img width="455" alt="gradient-safari" src="https://cloud.githubusercontent.com/assets/2294737/20023789/a29536c4-a2e2-11e6-9302-1dcf68743e2a.png">

**Comment by dmtrmrv** [comment]
Hi, thanks for submitting this. Will test and fix it as soon as I can.

**Comment by dmtrmrv** [comment]
Fixed in version 0.3.3
